/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import modelo.Maquina;
import modelo.EstadoMaquina;

/**
 *
 * @author Sergio Olmedo
 */
public class FormularioMaquina extends javax.swing.JFrame {

    /**
     * Creates new form FormularioMaquina
     */
    private VentanaPrincipal ventana;
    private Maquina maquinaAEditar;
    private boolean esEdicion = false;
    
    public FormularioMaquina(VentanaPrincipal ventana) {
    initComponents();
    setLocationRelativeTo(null);
    this.ventana = ventana;
    this.esEdicion = false;
    
    txtNombre.setText("");
    txtFecha.setText("");
    txtFrecuencia.setText("");
    
    configurarComboBox(); 
}
    
    public FormularioMaquina(VentanaPrincipal ventana,Maquina maquina) {
        initComponents();
    setLocationRelativeTo(null);
    this.ventana = ventana;
    this.maquinaAEditar = maquina;
    this.esEdicion = true;
    
    cmbTipo.removeAllItems();
    cmbTipo.addItem("Osciloscopio");
    cmbTipo.addItem("Fuente de Alimentación");
    cmbTipo.addItem("Multímetro");
    cmbTipo.addItem("Generador de Señales");
    
    txtNombre.setText(maquina.getNombre());
    cmbTipo.setSelectedItem(maquina.getTipo());
    txtFecha.setText(maquina.getFechaUltimoMantenimiento());
    txtFrecuencia.setText(String.valueOf(maquina.getFrecuenciaDia()));
    
    txtNombre.setText("");
    txtFecha.setText("");
    txtFrecuencia.setText(""); 
    
    // Configurar el combo (esto ya lo tienes bien)
    cmbTipo.removeAllItems(); // Opcional: limpiar items por defecto de NetBeans
    cmbTipo.addItem("Osciloscopio");
    cmbTipo.addItem("Fuente de Alimentación");
    cmbTipo.addItem("Multímetro");
    cmbTipo.addItem("Generador de Señales");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtFrecuencia = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre de la Maquina");

        jLabel2.setText("Tipo");

        jLabel3.setText("Ultimo Mantenimiento");

        jLabel4.setText("Frecuencia (Dias)");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        txtNombre.setText(" ");

        txtFecha.setText(" ");

        txtFrecuencia.setText("vacio");

        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });

        jLabel5.setText("dd/MM/aaaa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(btnGuardar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(txtNombre)))))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
       try { 
        String nombre = txtNombre.getText().trim();
        String tipo = cmbTipo.getSelectedItem().toString();
        String fecha = txtFecha.getText().trim();
        String frecStr = txtFrecuencia.getText().trim();

        if (nombre.isEmpty() || fecha.isEmpty() || frecStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
            return;
        }

        int frecuencia = Integer.parseInt(frecStr);

        if (esEdicion) {
            // --- MODO EDICIÓN ---
            // Modificamos directamente el objeto original en la lista
            maquinaAEditar.setNombre(nombre);
            maquinaAEditar.setTipo(tipo);
            maquinaAEditar.setFechaUltimoMantenimiento(fecha);
            maquinaAEditar.setFrecuenciaDia(frecuencia);
            
            // Le avisamos a la ventana principal que refresque la tabla
            ventana.actualizarTabla(); 
            javax.swing.JOptionPane.showMessageDialog(this, "Máquina actualizada correctamente");
        } else {
            // --- MODO NUEVO (Tu código anterior) ---
            EstadoMaquina estado = EstadoMaquina.AL_DIA;
            Maquina maquina = new Maquina(nombre, tipo, fecha, frecuencia, estado);
            ventana.agregarMaquina(maquina);
            javax.swing.JOptionPane.showMessageDialog(this, "Máquina registrada correctamente");
        }
        
        dispose();
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: La frecuencia debe ser un número entero.");
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged
        // TODO add your handling code here:
        if (cmbTipo.getSelectedItem() == null) {
        return; 
    }
        String tipo = cmbTipo.getSelectedItem().toString();
    
    switch (tipo) {
        case "Osciloscopio":
            txtFrecuencia.setText("90");
            break;
        case "Fuente de Alimentación":
            txtFrecuencia.setText("60");
            break;
        case "Multímetro":
            txtFrecuencia.setText("120");
            break;
        case "Generador de Señales":
            txtFrecuencia.setText("75");
            break;
        default:
            txtFrecuencia.setText("");
            break;
        }
    }//GEN-LAST:event_cmbTipoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioMaquina(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFrecuencia;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void configurarComboBox() {
    cmbTipo.removeAllItems();
    cmbTipo.addItem("Osciloscopio");
    cmbTipo.addItem("Fuente de Alimentación");
    cmbTipo.addItem("Multímetro");
    cmbTipo.addItem("Generador de Señales");
        }
}