/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.table.DefaultTableModel;
import modelo.Maquina;
import gui.FormularioMaquina;
import java.util.ArrayList;
import modelo.EstadoMaquina;

/**
 *
 * @author Sergio Olmedo
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private ArrayList<modelo.Maquina> listaMaquina;

    /**
     * Creates new form VentanaPrincipal
     */
    // Asegúrate de tener estos campos declarados al final de la clase (NetBeans lo hace solo)
// private javax.swing.JTable tablaMaquinas;
// private ArrayList<Maquina> listaMaquina;

public VentanaPrincipal() {
    initComponents();
    setLocationRelativeTo(null);
    
    // Configuración de la tabla
    String[] columnas = {"Nombre", "Tipo", "Últ. Mant.", "Frecuencia", "Estado"};
    DefaultTableModel modeloBase = new DefaultTableModel(columnas, 0);
    TablaMaquinas.setModel(modeloBase);
    
    listaMaquina = new ArrayList<>();
}
public void agregarMaquina(Maquina maquina) {
        // 1. Guardar en la lista
        listaMaquina.add(maquina);
        
        // 2. Actualizar la tabla
        actualizarTabla();
    }

    public void actualizarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) TablaMaquinas.getModel();
    modelo.setRowCount(0); 
    
    for (Maquina m : listaMaquina) {
        // Obtenemos el String del estado
        String estadoTexto = m.getEstado();
        
        // Personalizamos el mensaje si quieres que sea más amigable
        if(estadoTexto.equals("AL_DIA")) estadoTexto = "✅ Al Día";
        if(estadoTexto.equals("VENCIDO")) estadoTexto = "❌ Mantenimiento Vencido";
        if(estadoTexto.equals("PROXIMO_MANTENIMIENTO")) estadoTexto = "⚠️ Próximo (Menos de 7 días)";

        Object fila[] = {
            m.getNombre(),
            m.getTipo(),
            m.getFechaUltimoMantenimiento(),
            m.getFrecuenciaDia() + " días",
            estadoTexto
        };
        modelo.addRow(fila);
    }
}
   public void actualizarEstadosPorFecha(String fechaSimulada) {
    try {
        for (Maquina m : listaMaquina) {
            // Aquí enviamos la fecha que recibimos de la otra ventana
            EstadoMaquina nuevoEstado = m.calcularEstado(fechaSimulada);
            m.setEstado(nuevoEstado.name());
        }
        actualizarTabla();
    } catch (Exception e) {
        // Si sale el error, este mensaje te dirá qué TEXTO llegó realmente
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error: '" + fechaSimulada + "' no es una fecha válida.");
    }
}   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMaquinas = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de Mantenimiento Programado");

        TablaMaquinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Maquina", "Tipo", "Ultimo Mantenimiento", "Estado"
            }
        ));
        jScrollPane1.setViewportView(TablaMaquinas);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEstado.setText("Ver Estado");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(553, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEstado)
                            .addComponent(btnEditar)
                            .addComponent(btnAgregar)
                            .addComponent(btnEliminar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnEstado)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        // CORRECTO: 'this' le pasa la VentanaPrincipal actual al formulario
    FormularioMaquina form = new FormularioMaquina(this); // 'this' es la clave
    form.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        // TODO add your handling code here:
        VentanaSimulacion vSim = new VentanaSimulacion(this);
        vSim.setVisible(true);
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = TablaMaquinas.getSelectedRow();
        if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione una máquina de la tabla para editar.");
        return;
    }
       Maquina maquinaSeleccionada = listaMaquina.get(filaSeleccionada);
       FormularioMaquina formEditar = new FormularioMaquina(this, maquinaSeleccionada);
    formEditar.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = TablaMaquinas.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione la máquina que desea eliminar.");
        return;
    }
    
    int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea eliminar esta máquina?", 
            "Confirmar eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        listaMaquina.remove(filaSeleccionada);
        
        actualizarTabla();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Máquina eliminada correctamente.");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMaquinas;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
